#!/usr/bin/env python3
"""Append 10 approved agent-skill tools to tools.json."""
import json
from pathlib import Path

TOOLS_FILE = Path("/opt/data/martechsignal/tools/tools.json")
tools = json.loads(TOOLS_FILE.read_text())

today = "2026-07-31"

new_tools = [
    {
        "slug": "claude-seo",
        "name": "Claude SEO",
        "tagline": "Open-source SEO skill for Claude Code with 25 sub-skills and 18 parallel agents",
        "website": "https://claude-seo.md/",
        "category": "agent-skills",
        "pricing_model": "open-source",
        "pricing_url": None,
        "price_from": 0,
        "price_notes": "Free, MIT-licensed. Self-hosted inside Claude Code. Optional paid community mirror on Skool.",
        "ai_features": [
            "25 parallel sub-skills for technical SEO, E-E-A-T, schema, GEO/AEO",
            "18 specialist agents running concurrent audits",
            "AI search optimization (GEO) aligned with Google's AI Optimization Guide",
            "Citability scoring for AI-answer engines",
            "Falsifiable recommendations with dependency tracking"
        ],
        "integrations": ["Claude Code", "Google Search Console", "DataForSEO", "Firecrawl", "Lighthouse"],
        "github_repo": "AgriciDaniel/claude-seo",
        "github_stars": 12873,
        "open_source": True,
        "api_available": True,
        "founded": 2025,
        "hq": None,
        "status": "active",
        "date_added": today,
        "date_updated": today,
        "description": "Claude SEO turns Claude Code into an SEO audit machine. You type /seo audit and it spawns up to 15 specialist agents in parallel, each covering a different discipline: technical SEO, content quality, E-E-A-T signals, Schema.org markup, Core Web Vitals, local SEO, ecommerce SEO, international SEO, and AI search optimization (what Google calls GEO). A full-site audit that would take a consultant a full day finishes in minutes. The output is a prioritized action plan where every recommendation carries the observation it rests on, its dependencies, and an explicit \"how would we know this failed?\" check. That last part matters. Most SEO tools tell you what's wrong. Claude SEO tells you what's wrong, why it matters, and how you'd verify the fix worked.\n\nThe AI-search angle is what separates this from a Screaming Frog crawl. Claude SEO scores your content for citability by AI answer engines: whether your pages have self-contained 134-167 word answer blocks, question-based heading hierarchy, and the structured data that makes LLMs cite you instead of your competitor. It checks for IPTC TrainedAlgorithmicMedia metadata on AI-generated images, llms.txt files, and agent-friendly page structure per web.dev guidance. If you're optimizing for a world where Google's AI Overviews and ChatGPT answers replace traditional blue links, this is the audit tool built for that reality.\n\nIt's free and MIT-licensed. The catch is you need Claude Code (Anthropic's paid CLI/IDE product) to run it, so you're paying for API tokens. A full audit on a 200-page site burns through a meaningful chunk of tokens. There's also a private community mirror on Skool (AI Marketing Hub Pro) that gets early features, but the public repo is fully functional. Version 2.2.4 ships 410 passing tests, which is unusual rigor for a skill pack.\n\nCompared to doing this manually with Screaming Frog, Ahrefs, and a spreadsheet, Claude SEO collapses the workflow into one command. Compared to SaaS audit tools like Sitebulb or Lumar, it's more flexible and cheaper, but you lose the polished dashboards and historical tracking. It's best for SEO agencies running 5+ client sites who want weekly automated audits instead of quarterly manual ones, and for in-house SEO leads who want a second pair of eyes before executive reviews. If you don't use Claude Code, look at Codex SEO, the same author's port for OpenAI's Codex."
    },
    {
        "slug": "claude-ads",
        "name": "Claude Ads",
        "tagline": "Paid-media operations skill for Claude Code covering 12 ad platforms",
        "website": "https://github.com/AgriciDaniel/claude-ads",
        "category": "agent-skills",
        "pricing_model": "open-source",
        "pricing_url": None,
        "price_from": 0,
        "price_notes": "Free, MIT-licensed. Runs inside Claude Code. API costs for Claude apply.",
        "ai_features": [
            "250+ audit checks across 12 ad platforms",
            "Parallel subagent account audits with confidence scoring",
            "AI creative brief generation (copy, image, video, product photo)",
            "Campaign planning with budget allocation and measurement design",
            "Read-only by default with approval gates for live changes"
        ],
        "integrations": ["Google Ads", "Meta Ads", "YouTube Ads", "LinkedIn Ads", "TikTok Ads", "Microsoft Advertising", "Reddit Ads", "Snapchat Ads", "X Ads", "Apple Ads", "Amazon Ads", "Pinterest Ads"],
        "github_repo": "AgriciDaniel/claude-ads",
        "github_stars": 7719,
        "open_source": True,
        "api_available": True,
        "founded": 2025,
        "hq": None,
        "status": "active",
        "date_added": today,
        "date_updated": today,
        "description": "Claude Ads is a paid-media operations skill that runs inside Claude Code. Point it at your ad account exports or connect a read-only API feed, and it audits, plans, creates, monitors, and reports across 12 platforms: Google, Meta, YouTube, LinkedIn, TikTok, Microsoft, Reddit, Snapchat, X, Apple, Amazon, and Pinterest. Each platform gets its own focused skill, audit worker, and capability declaration. The audit alone runs 250+ checks and scores your account health with dated evidence and explicit confidence levels, so you know whether a finding is a confirmed problem or a likely one.\n\nThe workflow covers the full paid-media lifecycle. /ads audit gives you an evidence-backed account review. /ads plan builds channel strategy, campaign structure, budget allocation, and measurement design. /ads create produces copy, image briefs, video scripts, and product-photo directions. /ads monitor tracks pacing, delivery, fatigue, policy compliance, and performance drift. /ads experiment designs controlled tests. Everything outputs as versioned JSON that renders to Markdown, HTML, or PDF. The critical design choice: it's read-only by default. Live account changes stay disabled until the specific platform and operation pass approval, idempotency, verification, audit, and rollback gates. You draft changes with /ads launch --draft and /ads optimize --draft, review them, then decide whether to apply.\n\nIt's free and MIT-licensed, same as Claude SEO. You need Claude Code and API tokens. The context intake system asks about your industry and spend level upfront so benchmarks are relevant to your situation rather than generic. There's a community mirror on Skool for early access, but the public repo is complete.\n\nThe closest comparison is a human PPC consultant or an agency retainer. Claude Ads doesn't replace judgment, but it replaces the 4-hour manual audit spreadsheet and the \"I'll get to that creative brief next week\" backlog. For agencies managing multiple ad accounts, running /ads audit on each client monthly costs API tokens instead of billable hours. For in-house teams spending $5K-50K/month on ads, it's a force multiplier that catches wasted spend and policy violations before they compound. If you only run Meta ads and want a simpler tool, Revealbot handles rule-based automation. Claude Ads is for teams that want the full operational layer."
    },
    {
        "slug": "aaron-marketing-skills",
        "name": "Aaron Marketing Skills",
        "tagline": "120 marketing skills across 7 disciplines for Claude Code with auditor gates",
        "website": "https://github.com/aaron-he-zhu/aaron-marketing-skills",
        "category": "agent-skills",
        "pricing_model": "open-source",
        "pricing_url": None,
        "price_from": 0,
        "price_notes": "Free, Apache 2.0 licensed. Runs inside Claude Code and compatible agents.",
        "ai_features": [
            "120 skills across SEO/GEO, influencer, paid ads, email, launch, social, and brand narrative",
            "6 auditor gates (CORE-EEAT, CITE, C3, ROAS, SEND, RAMP) for quality scoring",
            "Auto-routing via /aaron-marketing:auto for natural-language goals",
            "Lifecycle phase directories (survey, implement, tune, evaluate)",
            "7 truth registries for entity, creator, offer, consent, launch, channel, and narrative"
        ],
        "integrations": ["Claude Code", "Codex", "Gemini CLI", "Cursor"],
        "github_repo": "aaron-he-zhu/aaron-marketing-skills",
        "github_stars": 2482,
        "open_source": True,
        "api_available": True,
        "founded": 2025,
        "hq": None,
        "status": "active",
        "date_added": today,
        "date_updated": today,
        "description": "Aaron Marketing Skills is a 120-skill library that turns Claude Code into a marketing operator across seven disciplines: brand narrative, SEO/GEO, social, email, paid ads, influencer, and product launch. Each discipline follows a lifecycle with phase directories. SEO goes survey, implement, tune, evaluate. Email goes setup, engage, nurture, deliver. Paid ads goes research, orchestrate, activate, scale. The /aaron-marketing:auto command routes any natural-language goal to the right skill, so you don't memorize 120 slash commands.\n\nWhat makes this different from a prompt pack is the protocol layer. Eight shared commands and seven truth registries (entity, creator, offer/claims, consent, launch, channel, narrative) enforce consistency across skills. Six auditor gates score output quality: CORE-EEAT for content, CITE for domain authority, C3 for creative, ROAS for ad accounts, SEND for email, and RAMP for launches. Skills and commands are plain Markdown. Small Bash and Python-stdlib runtimes handle hooks, validation, scoring, and CI checks. No pip, no build step. Every skill runs self-contained.\n\nInstallation is a git clone into your skills directory. It works on Claude Code, Codex, Gemini CLI, and Cursor. The README is available in 10 languages, which hints at the author's ambition. Version 19.0.0 is current as of late July 2026, and the repo was pushed to today, so maintenance is active.\n\nThe trade-off with 120 skills is depth versus breadth. Each discipline gets 16 skills, which is enough for structured workflows but not the 158-skill depth of Digital Marketing Pro or the platform-specific granularity of Claude Ads. If you want one skill pack that covers everything marketing at a competent level, this is it. If you need deep paid-media operations specifically, Claude Ads goes further on that vertical. If you're an agency that needs brand narrative and launch planning alongside the performance channels, Aaron's lifecycle structure and auditor gates give you a framework that the narrower tools don't."
    },
    {
        "slug": "ai-marketing-claude",
        "name": "AI Marketing Suite",
        "tagline": "15-skill marketing suite for Claude Code with parallel agents and PDF reports",
        "website": "https://github.com/zubair-trabzada/ai-marketing-claude",
        "category": "agent-skills",
        "pricing_model": "open-source",
        "pricing_url": None,
        "price_from": 0,
        "price_notes": "Free. Optional pip install reportlab for PDF output. Claude API costs apply.",
        "ai_features": [
            "15 marketing skills with 5 parallel subagents",
            "Full website marketing audit with 0-100 scoring",
            "AI copywriting with before/after examples",
            "Email sequence and content calendar generation",
            "Client-ready PDF report generation"
        ],
        "integrations": ["Claude Code"],
        "github_repo": "zubair-trabzada/ai-marketing-claude",
        "github_stars": 2242,
        "open_source": True,
        "api_available": False,
        "founded": 2025,
        "hq": None,
        "status": "active",
        "date_added": today,
        "date_updated": today,
        "description": "AI Marketing Suite is a 15-skill pack for Claude Code aimed at solopreneurs and agency builders who want to sell marketing services. You type /market audit https://example.com and five parallel agents analyze content and messaging, conversion optimization, SEO and discoverability, competitive positioning, and brand trust. Each gets a 0-100 score. The whole thing takes a couple of minutes and outputs a structured Markdown report. Add pip install reportlab and you get a client-ready PDF.\n\nThe 15 commands cover the freelance marketing toolkit: /market copy generates optimized copy with before/after examples, /market emails builds complete email sequences, /market social produces a 30-day content calendar, /market ads writes ad creative for all platforms, /market funnel analyzes conversion paths, /market competitors runs competitive intelligence, /market landing does CRO analysis, /market launch builds a product launch playbook, and /market proposal generates client proposals. It's built for the person who just landed a marketing client and needs to deliver an audit by Friday.\n\nSetup is a one-line curl install or a git clone. The architecture is straightforward: one orchestrator SKILL.md routes commands to 14 sub-skills, and 5 parallel subagents handle the audit dimensions. No external dependencies beyond Claude Code itself, unless you want PDF output.\n\nThe limitation is depth. Fifteen skills is a survey, not a specialization. The SEO audit won't match Claude SEO's 25 sub-skills and 18 agents. The ad copy won't match Claude Ads' 250+ platform-specific checks. But for a generalist who needs to audit a website, write some copy, build an email sequence, and hand over a PDF report, this does the job in one install. The repo was last pushed in March 2026, so it's not as actively maintained as some alternatives. The author also ships companion packs for ads (ai-ads-claude) and sales (ai-sales-team-claude) if you want to go deeper on those verticals."
    },
    {
        "slug": "digital-marketing-pro",
        "name": "Digital Marketing Pro",
        "tagline": "158-skill AI marketing plugin for agencies with EU AI Act compliance",
        "website": "https://github.com/indranilbanerjee/digital-marketing-pro",
        "category": "agent-skills",
        "pricing_model": "open-source",
        "pricing_url": None,
        "price_from": 0,
        "price_notes": "Free, MIT-licensed. Runs on Claude Code, Codex, Cursor, Copilot CLI, and 35+ agent platforms.",
        "ai_features": [
            "158 skills with 24 specialist agents",
            "12-Part Strategy Flow with Four Core Documents",
            "EU AI Act Article 50 compliance (C2PA, AI disclosure)",
            "Cowork team-persistent state",
            "61-step engagement structure per brand"
        ],
        "integrations": ["Claude Code", "Anthropic Cowork", "OpenAI Codex", "Cursor", "GitHub Copilot CLI", "Google Antigravity", "Hermes Agent", "OpenClaw"],
        "github_repo": "indranilbanerjee/digital-marketing-pro",
        "github_stars": 670,
        "open_source": True,
        "api_available": True,
        "founded": 2025,
        "hq": None,
        "status": "active",
        "date_added": today,
        "date_updated": today,
        "description": "Digital Marketing Pro is the heaviest skill pack in this category: 158 skills, 24 specialist agents, 18 commands, and 86 scripts. It's built for agencies and in-house teams managing 50-200 brands. The core workflow is a 12-Part Strategy Flow that produces Four Core Documents per brand, following a 61-step structure. Run /digital-marketing-pro:engagement against a brand and you get a full strategy engagement in roughly 60 minutes on an Opus-class model. The pitch is consistency: same depth, same structure, same audit trail across your entire portfolio, whether you have 3 brands or 200.\n\nThe compliance angle is what makes this interesting for agencies operating in regulated markets. Version 3.17.0 (July 2026) ships EU AI Act Article 50 readiness, including C2PA content provenance and an --ai-disclosure flag for generated content. The v3.15.0 release before it purged fictional npm packages, added uniform typed-approval gates across all 18 execution skills, and consolidated agents from 25 to 24. The changelog reads like someone who takes reliability seriously. 209 out of 209 tests pass. A 16-reader audit fleet re-verified all 530 files against July 2026 ground truth and shipped roughly 250 fixes.\n\nIt installs on eight native platforms (Claude Code, Cowork, Codex, Cursor, Copilot CLI, Antigravity, Hermes Agent, OpenClaw) plus 35 more via the Agent Skills open standard. The Cowork integration means team-persistent state: your brand documents and strategy context survive across sessions and team members. That's a real workflow feature, not a checkbox.\n\nThe trade-off is complexity. 158 skills is a lot to learn. The README opens with a scenario about a 50-brand client and a bleeding budget, which tells you the intended user: someone who already knows marketing strategy and wants to scale its execution. If you're a solo freelancer auditing one website, AI Marketing Suite's 15 commands will get you there faster. If you're an agency that needs auditable, compliant, consistent strategy work across a portfolio, this is the only skill pack built for that."
    },
    {
        "slug": "ai-business-skills",
        "name": "AI Business Skills",
        "tagline": "63 bilingual marketing skills (Vietnamese + Global) for Claude Code and agents",
        "website": "https://github.com/minhnv0807/ai-business-skills",
        "category": "agent-skills",
        "pricing_model": "open-source",
        "pricing_url": None,
        "price_from": 0,
        "price_notes": "Free, MIT-licensed. Runs on Claude Code, OpenCode, Codex, and VS Code.",
        "ai_features": [
            "63 bilingual skills (31 Vietnamese + 31 Global + 1 Design Master)",
            "Marketing planning with VN 2025-2026 benchmarks and 3-scenario KPIs",
            "AI avatar and personal brand production",
            "8 design types via prompt-driven workflow",
            "Competitor analysis with 48-hour action plans"
        ],
        "integrations": ["Claude Code", "OpenCode", "Codex", "VS Code"],
        "github_repo": "minhnv0807/ai-business-skills",
        "github_stars": 513,
        "open_source": True,
        "api_available": False,
        "founded": 2025,
        "hq": None,
        "status": "active",
        "date_added": today,
        "date_updated": today,
        "description": "AI Business Skills is a bilingual marketing skill pack built by Over Powers Agency, a Vietnamese marketing shop. It ships 63 skills split between Vietnamese-market and global-market variants, plus a Design Master skill covering 8 design types (personal brand, business logo, campaign visual, social post, editorial, infographic, web mockup, quote graphic). The Vietnamese-first angle is the differentiator: marketing plans come with VN 2025-2026 benchmarks, local platform context (Facebook and TikTok dominate in Vietnam), and budget allocations that make sense for the market.\n\nThe skills cover planning, campaign briefs, copywriting (Facebook/TikTok ads, video scripts, email, landing pages), personal brand strategy, competitor analysis, customer insight, ad audits, and dropshipping. Each outputs a structured Markdown file with KPIs across three scenarios, budget allocation, weekly timelines, and risk matrices. The install is a bash script that drops 63 skills into ~/.claude/skills/marketing/. Windows gets a PowerShell equivalent.\n\nIt works on Claude Code, OpenCode, Codex, and VS Code. The repo was pushed to on July 30, 2026, so it's actively maintained. Version 2.7.0 added the Design Master skill with zero breaking changes. The companion OPA KIT repo bundles the full build-and-market stack.\n\nIf you're marketing to Vietnamese audiences or running a Vietnamese-language operation, this is the only skill pack in this directory that speaks the language natively, not as a translation layer. The global skills are competent but less distinctive. Against Aaron Marketing Skills' 120 skills, this has fewer but goes deeper on the Vietnamese market context. For English-only teams, Aaron or Digital Marketing Pro will serve better. For anyone doing business in Vietnam or Southeast Asia, this fills a gap nothing else addresses."
    },
    {
        "slug": "codex-seo",
        "name": "Codex SEO",
        "tagline": "Codex-first SEO skill suite with 26 workflows, 24 TOML agents, and API integrations",
        "website": "https://github.com/AgriciDaniel/codex-seo",
        "category": "agent-skills",
        "pricing_model": "open-source",
        "pricing_url": None,
        "price_from": 0,
        "price_notes": "Free, MIT-licensed. Runs inside OpenAI Codex. Python 3.10+ required.",
        "ai_features": [
            "26 SEO workflows with 24 TOML agent profiles",
            "DataForSEO, Gemini, Google API, and Firecrawl integrations",
            "GEO/AEO optimization for AI search",
            "Core Web Vitals and technical SEO audits",
            "Deterministic headless runners for repeatable execution"
        ],
        "integrations": ["OpenAI Codex", "DataForSEO", "Google Search Console", "Firecrawl", "Gemini"],
        "github_repo": "AgriciDaniel/codex-seo",
        "github_stars": 534,
        "open_source": True,
        "api_available": True,
        "founded": 2025,
        "hq": None,
        "status": "active",
        "date_added": today,
        "date_updated": today,
        "description": "Codex SEO is the OpenAI Codex port of Claude SEO, built by the same author (AgriciDaniel). It covers the same SEO surface: technical audits, on-page analysis, E-E-A-T content quality, schema markup, Core Web Vitals, GEO/AEO for AI search, backlinks, local SEO, ecommerce SEO, hreflang, and semantic clustering. The difference is the runtime. Instead of Claude Code's subagent model, Codex SEO uses 24 TOML agent profiles, deterministic headless runners, and a Python virtualenv at ~/.codex/skills/seo/.venv/. If your team runs Codex instead of Claude Code, this is the same workflow adapted to your platform.\n\nThe integration surface is wider than Claude SEO's. Codex SEO connects to DataForSEO for keyword and SERP data, Google Search Console for performance metrics, Firecrawl for page crawling, and Gemini for image analysis workflows. The headless runners mean you can script audits in CI or run them on a schedule without an interactive terminal. 52 tests pass, and the installer handles dependency setup, capability groups, and runtime verification.\n\nInstallation is a one-line curl (or PowerShell on Windows). The installer copies skills into ~/.codex/skills/, agents into ~/.codex/agents/, creates the virtualenv, and installs dependencies. Current release is v1.9.6-codex.5, synchronized to Claude SEO upstream at commit a9cf338.\n\nIf you're choosing between this and Claude SEO, the decision is simple: use whichever matches your agent platform. The SEO methodology is the same. Codex SEO adds the DataForSEO and Firecrawl integrations that Claude SEO handles through its own extension system. For teams already paying for OpenAI's Codex, this avoids the cost of switching to Claude Code just for SEO audits. The star count (534) is lower than Claude SEO's 12,873, which reflects the smaller Codex user base, not a quality gap."
    },
    {
        "slug": "email-marketing-bible",
        "name": "Email Marketing Bible",
        "tagline": "55K-word email marketing skill with 908 sources, 19 playbooks, and ESP control via MCP",
        "website": "https://github.com/CosmoBlk/email-marketing-bible",
        "category": "agent-skills",
        "pricing_model": "open-source",
        "pricing_url": None,
        "price_from": 0,
        "price_notes": "Free and open source. Works with Claude Code, Claude Desktop, and MCP-compatible agents.",
        "ai_features": [
            "55K-word knowledge base from 908 sources",
            "19 industry-specific playbooks with benchmarks",
            "AI copy drafting with anti-slop rules",
            "ESP control via MCP (Klaviyo, Mailchimp, Resend, beehiiv, Omnisend, nitrosend)",
            "Deliverability triage and compliance gating (GDPR, CAN-SPAM, CASL, CCPA)"
        ],
        "integrations": ["Klaviyo", "Mailchimp", "Resend", "beehiiv", "Omnisend", "nitrosend", "Claude Code", "MCP"],
        "github_repo": "CosmoBlk/email-marketing-bible",
        "github_stars": 251,
        "open_source": True,
        "api_available": True,
        "founded": 2026,
        "hq": None,
        "status": "active",
        "date_added": today,
        "date_updated": today,
        "description": "Email Marketing Bible is what happens when someone who ran an email SaaS (SmartrMail, ~28,000 customers, 6 billion emails sent, acquired in 2022) distills everything into a 55,000-word skill file. It's not a prompt pack. It's a knowledge base with 908 cited sources, 19 industry playbooks, and 47 curated email designs. Install it and your AI agent stops guessing about email. It knows what a good open rate is for your vertical, why your emails land in spam, and which flow to build first for a DTC skincare brand doing $2M/year.\n\nThe practical capabilities: it builds welcome, cart, post-purchase, and win-back flows from a prompt, then reviews exits, timing, and copy before anything goes live. It audits your ESP setup for missing flows, broken segments, and deliverability problems. It drafts copy using proven frameworks (PAS, AIDA, BAB) and strips AI tells before send. The anti-slop rules are explicit: no \"we hope this email finds you well,\" no generic personalization, no AI voice. It designs emails in MJML or React Email with dark-mode and mobile checks. And it drives your ESP through MCP connectors for Klaviyo, Mailchimp, Resend, beehiiv, Omnisend, and nitrosend, with a hard rule that nothing sends without your approval.\n\nInstallation is one git clone into ~/.claude/skills/. It works wherever the skill format is read: Claude Code, Claude Desktop, and MCP-compatible agents. The compliance gate covers GDPR, CAN-SPAM, CASL, CCPA, and the Australian Spam Act as a decision gate before any send. That's not a feature list item. It's a workflow step that blocks non-compliant campaigns.\n\nAgainst a SaaS tool like Klaviyo or Mailchimp, this doesn't replace the ESP. It makes the AI operating the ESP competent. Against hiring an email consultant, it's cheaper and available at 2am. The 19 industry playbooks mean a nonprofit gets different advice than a B2B SaaS company. The limitation is that it's a knowledge layer, not an execution platform. You still need an ESP and an agent runtime. But if you're already running Claude Code and an ESP, this is the difference between your agent sending generic slop and sending email that actually converts."
    },
    {
        "slug": "openclaw-marketing-skills",
        "name": "OpenClaw Marketing Skills",
        "tagline": "37 marketing skills for OpenClaw agents with live data connectors",
        "website": "https://github.com/LeoYeAI/openclaw-marketing-skills",
        "category": "agent-skills",
        "pricing_model": "open-source",
        "pricing_url": None,
        "price_from": 0,
        "price_notes": "Free, MIT-licensed. Runs on OpenClaw agents. Cloud hosting available via MyClaw.ai.",
        "ai_features": [
            "37 skills covering CRO, copywriting, SEO, paid ads, email, growth, retention, sales, strategy",
            "Live data connectors for Google Ads, Search Console, Meta Ads, and X/Twitter",
            "Product-aware skills that read your codebase",
            "Creative fatigue detection and audience overlap triage",
            "Keyword cannibalization detection"
        ],
        "integrations": ["OpenClaw", "Google Ads API", "Google Search Console", "Meta Marketing API", "X/Twitter (TweetClaw)", "MyClaw.ai"],
        "github_repo": "LeoYeAI/openclaw-marketing-skills",
        "github_stars": 1075,
        "open_source": True,
        "api_available": True,
        "founded": 2025,
        "hq": None,
        "status": "active",
        "date_added": today,
        "date_updated": today,
        "description": "OpenClaw Marketing Skills gives OpenClaw agents a full marketing brain: 37 skills across CRO, copywriting, SEO, paid ads, email, growth, retention, sales, and strategy. The skills read your actual codebase and product context, so the output is specific to what you're building rather than generic marketing advice. The README's pitch is blunt: \"Not advice. Output.\" And the data connectors back that up. Connect your Google Ads, Search Console, Meta Ads, or X/Twitter accounts, and the skills work with real numbers instead of assumptions.\n\nThe four data connectors are the headline feature. google-ads-connect audits campaigns, finds wasted spend, and identifies zero-conversion keywords. search-console-connect diagnoses traffic drops, surfaces quick-win keywords, and detects cannibalization. meta-ads-connect catches creative fatigue, triages Learning Phase issues, and flags audience overlap. x-twitter-connect searches conversations, monitors keywords, and drafts reviewed responses. The README explicitly compares this to Toprank (2.6K stars), noting that Toprank covers Google/Meta ads and SEO data but misses X/Twitter signals and the 28 additional skills covering the rest of the marketing stack.\n\nIt's MIT-licensed and runs on OpenClaw agents. MyClaw.ai offers cloud-hosted OpenClaw with one-click setup if you don't want to manage a server. The repo was last pushed in June 2026, so it's a few weeks behind the most actively maintained packs in this list. The README is available in 5 languages.\n\nThe OpenClaw dependency is the constraint. If you're running Claude Code or Codex, you'd use Claude SEO, Claude Ads, or Aaron Marketing Skills instead. OpenClaw Marketing Skills is for teams already on OpenClaw or evaluating it. Within that ecosystem, the data connectors give it an edge over generic skill packs that operate on prompts alone. The 37-skill count sits between the focused tools (Claude SEO's 25, AI Marketing Suite's 15) and the comprehensive ones (Aaron's 120, Digital Marketing Pro's 158). It's a solid middle ground if OpenClaw is your platform."
    },
    {
        "slug": "analytics-tracking-automation",
        "name": "Analytics Tracking Automation",
        "tagline": "AI skill for GA4 + GTM event tracking: site analysis, schema design, and go-live",
        "website": "https://www.jtracking.ai/skills",
        "category": "agent-skills",
        "pricing_model": "open-source",
        "pricing_url": None,
        "price_from": 0,
        "price_notes": "Free. Runs on Cursor, Codex, and any AI agent. npm-based install.",
        "ai_features": [
            "Automated site analysis and page grouping by business purpose",
            "GA4 event schema design and review",
            "GTM-ready output generation with verification guidance",
            "Shopify storefront support",
            "Artifact-backed progress that can be resumed"
        ],
        "integrations": ["GA4", "Google Tag Manager", "Cursor", "Codex", "Shopify"],
        "github_repo": "jtrackingai/analytics-tracking-automation",
        "github_stars": 134,
        "open_source": True,
        "api_available": True,
        "founded": 2025,
        "hq": None,
        "status": "active",
        "date_added": today,
        "date_updated": today,
        "description": "Analytics Tracking Automation solves a specific, annoying problem: setting up GA4 and GTM event tracking correctly. Most marketing teams either skip proper tracking setup or pay a consultant $2,000 to do it. This skill automates the workflow from site analysis to go-live. You give it a URL, and it analyzes the site, groups pages by business purpose, designs a GA4 event schema, produces GTM-ready outputs, and walks you through verification before publishing. It handles both generic websites and Shopify storefronts.\n\nThe workflow is artifact-backed, meaning each step produces a reviewable file you can inspect before moving on. The site analysis groups pages into business categories (product, checkout, blog, support) so the event schema maps to actual user journeys rather than generic pageview tracking. The GTM output includes the container configuration, trigger definitions, and variable setup. Verification guidance tells you what to check in GTM preview mode before you publish. If you stop halfway through, the artifacts let you resume where you left off.\n\nInstallation is npm-based: clone the repo and run npm run install:skills, or use npx skills add jtrackingai/analytics-tracking-automation for a no-clone install. It works on Cursor, Codex, and any agent that reads the skill format. The ClawHub publish path strips executable runtime files for marketplace safety.\n\nThis is the narrowest tool in this batch, and that's its strength. It doesn't try to be a full marketing suite. It does one thing that every marketing team needs and few do well. At 134 stars, it's the smallest repo here, and the last push was April 2026, so it's not getting weekly updates. But the problem it solves doesn't change often. GA4's event model is stable, GTM's container format is stable, and the workflow from \"we need tracking\" to \"tracking is live and verified\" is well-defined. If you're setting up analytics for a new site or auditing an existing GTM mess, this saves you a day of spreadsheet work and a week of \"is this firing correctly?\" anxiety."
    }
]

tools.extend(new_tools)
TOOLS_FILE.write_text(json.dumps(tools, indent=2, ensure_ascii=False))
print(f"Added {len(new_tools)} tools. Total: {len(tools)}")
