#!/usr/bin/env python3
"""Generate the two missing directory index pages (R2 card L-7).

Before this, /categories/ and /authors/ both returned 404 even though category
pages and author pages exist beneath them - so inbound links to the indexes died.

Outputs:
  - categories/index.html   (all categories with tool counts + descriptions)
  - authors/index.html      (author list -> /authors/tim-christensen/)

Reuses page_shell from build_tools so the footer/masthead stay canonical.
"""
import json
from pathlib import Path

from build_tools import page_shell, esc, ROOT

TOOLS_DIR = ROOT / "tools"


def load():
    cats = json.loads((TOOLS_DIR / "categories.json").read_text())
    tools = json.loads((TOOLS_DIR / "tools.json").read_text())
    return cats, tools


def build_categories(cats, tools):
    total = len(tools)
    cards = []
    for c in sorted(cats, key=lambda x: x["name"]):
        n = len(c.get("tools") or [])
        desc = esc(c.get("description") or "")
        cards.append(
            f'<a class="tool-card" href="/categories/{c["slug"]}/">'
            f'<div class="name">{esc(c["name"])}</div>'
            f'<div class="tagline">{desc}</div>'
            f'<div class="tagline">{n} tool{"s" if n != 1 else ""}</div></a>'
        )
    body = (
        '<header class="page-head"><h1>Categories</h1>'
        f'<p class="lede">All {len(cats)} categories across the {total}-tool directory. '
        'Each category page lists its tools with licence, stars and a plain summary of what it does.</p></header>'
        f'<div class="tool-grid">{"".join(cards)}</div>'
    )
    schema = {
        "@context": "https://schema.org",
        "@type": "CollectionPage",
        "name": "Categories",
        "url": "https://martechsignal.com/categories/",
        "description": f"All {len(cats)} tool categories in the MartechSignal directory.",
    }
    return page_shell(
        "Categories | MartechSignal",
        f"Browse all {len(cats)} categories across {total} marketing-automation tools: licences, stars and plain-English summaries.",
        "/categories/",
        body, schema_json=schema, og_image="og.png",
    )


def build_authors():
    body = (
        '<header class="page-head"><h1>Authors</h1>'
        '<p class="lede">Who writes MartechSignal, and what the hands-on test standard is.</p></header>'
        '<div class="tool-grid">'
        '<a class="tool-card" href="/authors/tim-christensen/">'
        '<div class="name">Tim Christensen</div>'
        '<div class="tagline">Founder. Writes the tool teardowns and the automation audits. '
        'Roughly 19 years in marketing technology, currently working in MarTech and platform product ownership.</div></a>'
        '</div>'
    )
    schema = {
        "@context": "https://schema.org",
        "@type": "CollectionPage",
        "name": "Authors",
        "url": "https://martechsignal.com/authors/",
        "description": "MartechSignal authors.",
    }
    return page_shell(
        "Authors | MartechSignal",
        "Who writes MartechSignal: the people behind the tool teardowns and automation audits.",
        "/authors/",
        body, schema_json=schema, og_image="og.png",
    )


def build_homepage_strip(cats):
    """Rewrite the 'Browse by category' strip on the homepage (R2 card L-8).

    Idempotent: replaces between markers if present, otherwise inserts before the
    subscribe section. Only real internal linking is added here - no decorative
    image, because the homepage has no designed asset for one (0 <img> in source
    is a deliberate call, not an oversight).
    """
    cards = []
    for c in sorted(cats, key=lambda x: x["name"]):
        n = len(c.get("tools") or [])
        cards.append(
            f'<a class="tool-card" href="/categories/{c["slug"]}/">'
            f'<div class="name">{esc(c["name"])}</div>'
            f'<div class="tagline">{n} tool{"s" if n != 1 else ""}</div></a>'
        )
    strip = (
        "<!-- categories-strip:start (generated by tools/build_indexes.py) -->\n"
        '<section class="section">\n'
        '<h2>Browse by category</h2>\n'
        f'<p class="lede">The directory covers {len(cats)} categories. '
        'Each one lists its tools with licence, stars and a plain summary of what the tool does.</p>\n'
        f'<div class="tool-grid">{"".join(cards)}</div>\n'
        '<p class="lede"><a href="/categories/">All categories</a> · <a href="/tools/">Full tool directory</a></p>\n'
        "</section>\n"
        "<!-- categories-strip:end -->"
    )
    p = ROOT / "index.html"
    html = p.read_text()
    start = "<!-- categories-strip:start"
    end = "<!-- categories-strip:end -->"
    if start in html and end in html:
        i = html.index(start)
        j = html.index(end) + len(end)
        html = html[:i] + strip + html[j:]
        action = "replaced existing strip"
    else:
        anchor = '<section class="subscribe"'
        assert html.count(anchor) == 1, f"ASSERT: expected 1 subscribe anchor, found {html.count(anchor)}"
        html = html.replace(anchor, strip + "\n\n" + anchor)
        action = "inserted strip before subscribe"
    p.write_text(html)
    return action


def main():
    cats, tools = load()
    for slug, html in (("categories", build_categories(cats, tools)), ("authors", build_authors())):
        d = ROOT / slug
        d.mkdir(parents=True, exist_ok=True)
        (d / "index.html").write_text(html)
        print(f"  wrote {slug}/index.html ({len(html)} bytes)")
    print(f"  homepage strip: {build_homepage_strip(cats)}")
    print(f"index pages built from {len(cats)} categories / {len(tools)} tools")


if __name__ == "__main__":
    main()
